apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-cleanup-operator-manager-rolebinding
  labels:
    app.kubernetes.io/name: pod-cleanup-operator
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-cleanup-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: pod-cleanup-operator
    namespace: pod-cleanup-operator-system
