apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pod-cleanup-operator-system

resources:
  - crd/bases
  - rbac/service_account.yaml
  - rbac/role.yaml
  - rbac/role_binding.yaml
  - manager/manager.yaml
